name: Construir imagen y subirla a Docker Hub

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v3
      - name: Login en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: docker/setup-buildx-action@v2
          uses: Construir imagen y subirla
        - name: docker/build-push-action@v4
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: |
              ${{ secrets.DOCKERHUB_USERNAME }}/docker-github-actions:latest
              ${{ secrets.DOCKERHUB_USERNAME }}/docker-github-actions:${{ github.sha }}